title: "Istomin's Blog"
email: "aistomin.blog@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  It's a personal blog of Andrej Istomin.
baseurl: ""
url: "http://aistomin.github.io/"
github_username: "aistomin"
so_id: "1842599"
facebook_username:  "andrej30000"
instagram_username:  "andrej.istomin"
linkedin_username: "andrej-istomin-51ba7530"
twitter_username: "aistomin3"
google_id: "100948245902150777435"
youtube_id: "UC_Xbh9rT4YiFL4U84oalEjQ"
pinterest_id: "andrejistomin"
upwork_id: "013da7713f9077c1db"
markdown: kramdown
copyright: "© 2015-2023 Andrej Istomin"
year: "2015"
paginate: 10

plugins:
 - jekyll-paginate
 - kramdown
