title: "Istomin's Blog"
email: "aistomin.blog@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  It's a personal blog of Andrej Istomin.
baseurl: ""
url: "http://aistomin.github.io/"
github_username: "aistomin"
facebook_username:  "andrej.istomin.3"
linkedin_username: "andrej-istomin-51ba7530"
google_id: "100948245902150777435"
markdown: kramdown
copyright: "© 2015-2016 Andrej Istomin"
year: "2015"